lab08/lab08/Models/ErrorViewModel.cs
namespace lab08.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lab08/lab08/Models/NlcAccount.cs
using System.ComponentModel.DataAnnotations;

namespace lab08.Models
{
    public class NlcAccount
    {
        [Key]
        public int NlcId { get; set; }

        [Display(Name = "Họ và tên")]
        [Required(ErrorMessage = "Họ không được để trống")]
        [MinLength(6, ErrorMessage = "Họ tên ít nhất là 6 ký tự")]
        [MaxLength(20, ErrorMessage = "Họ tên tối đa 20 ký tự")]
        public string NlcFullName { get; set; }

        [Display(Name = "Địa chỉ email")]
        [Required(ErrorMessage = "Địa chỉ email không được để trống")]
        [EmailAddress(ErrorMessage = "Địa chỉ email không đúng định dạng")]
        
        public string NlcEmail { get; set; }

        [Display(Name = "Số điện thoại")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^(\(?[0-9]{3}\)?)[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
            ErrorMessage = "Số điện thoại không đúng định dạng")]
        [Required(ErrorMessage = "Số điện thoại không được để trống")]
        public string NlcPhone { get; set; }

        [Display(Name = "Địa chỉ thường trú")]
        [Required(ErrorMessage = "Địa chỉ không được để trống")]
        [StringLength(35, ErrorMessage = "Địa chỉ không vượt quá 35 ký tự")]
        public string NlcAddress { get; set; }

        [Display(Name = "Ảnh đại diện")]
        public string NlcAvatar { get; set; }

        [Display(Name = "Ngày sinh")]
        [Required(ErrorMessage = "Ngày sinh không được để trống")]
        [DataType(DataType.Date)]
        public DateTime NlcBirthday { get; set; }

        [Display(Name = "Giới tính")]
        public string NlcGender { get; set; }

        [Display(Name = "Mật khẩu")]
        [DataType(DataType.Password)]
        public string NlcPassword { get; set; }

        [Display(Name = "Link Facebook cá nhân")]
        [Required(ErrorMessage = "Link Facebook không được để trống")]
        [Url(ErrorMessage = "Url phải đúng định dạng bao gồm http hoặc https, tên miền VD: https://facebook.com/ten")]
        public string NlcFacebook { get; set; }
    }
}

lab08/lab08/Controllers/NlcAccountController.cs
using lab08.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Reflection;

namespace lab08.Controllers
{
    
    public class NlcAccountController : Controller
    {
        private static List<NlcAccount> nlcListAccount = new List<NlcAccount>
{
    new NlcAccount
    {
        NlcId = 1,
        NlcFullName = "Nguyễn Linh Chi",
        NlcEmail = "nguyenlinhchi022@gmail.com",
        NlcPhone = "0366084921",
        NlcAddress = "12 lí ải, song phương, hoài đức, hà nội",
        NlcAvatar = "avatar1.jpg",
        NlcBirthday = new DateTime(2005, 1, 24),
        NlcGender = "Nam",
        NlcPassword = "An123456",
        NlcFacebook = "https://facebook.com/nguyenvanan"
    },
    new NlcAccount
    {
        NlcId = 2,
        NlcFullName = "Trần Thị Bích",
        NlcEmail = "bich.tran@example.com",
        NlcPhone = "091-987-6543",
        NlcAddress = "456 Nguyễn Trãi, TP.HCM",
        NlcAvatar = "avatar2.png",
        NlcBirthday = new DateTime(1993, 8, 21),
        NlcGender = "Nữ",
        NlcPassword = "Bich123456",
        NlcFacebook = "https://facebook.com/tranthibich"
    },
    new NlcAccount
    {
        NlcId = 3,
        NlcFullName = "Phạm Quốc Hùng",
        NlcEmail = "hung.pham@example.com",
        NlcPhone = "092-333-4444",
        NlcAddress = "789 Phan Đình Phùng, Huế",
        NlcAvatar = "avatar3.jpg",
        NlcBirthday = new DateTime(1990, 12, 5),
        NlcGender = "Nam",
        NlcPassword = "Hung123456",
        NlcFacebook = "https://facebook.com/phamquochung"
    },
    new NlcAccount
    {
        NlcId = 4,
        NlcFullName = "Lê Minh Châu",
        NlcEmail = "chau.le@example.com",
        NlcPhone = "093-888-9999",
        NlcAddress = "12 Hai Bà Trưng, Đà Nẵng",
        NlcAvatar = "avatar4.png",
        NlcBirthday = new DateTime(1998, 2, 10),
        NlcGender = "Nữ",
        NlcPassword = "Chau123456",
        NlcFacebook = "https://facebook.com/leminhchau"
    },
    new NlcAccount
    {
        NlcId = 5,
        NlcFullName = "Đỗ Thanh Tùng",
        NlcEmail = "tung.do@example.com",
        NlcPhone = "094-222-3333",
        NlcAddress = "68 Trần Hưng Đạo, Cần Thơ",
        NlcAvatar = "avatar5.jpg",
        NlcBirthday = new DateTime(1992, 7, 30),
        NlcGender = "Nam",
        NlcPassword = "Tung123456",
        NlcFacebook = "https://facebook.com/dothanhtung"
    }
        };


        public ActionResult NlcIndex()
        {
            return View(nlcListAccount);
        }

        // GET: NlcAccountController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: NlcAccountController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NlcAccountController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]

        
        public ActionResult Create(NlcAccount model)
        {
            if (!ModelState.IsValid)
            {
                return View(model); // Trả lại view kèm lỗi nếu validation fail
            }

            model.NlcId = nlcListAccount.Count + 1;
            nlcListAccount.Add(model);

            return RedirectToAction(nameof(NlcIndex));
        }

      
        // GET: NlcAccountController/Edit/5
        public ActionResult Edit(int id)
        {
            var acc = nlcListAccount.FirstOrDefault(x => x.NlcId == id);
            if (acc == null)
            {
                return NotFound();
            }
            return View(acc); // truyền dữ liệu vào view để hiển thị form sửa
        }

        // POST: NlcAccountController/Edit/5
        [HttpPost]
[ValidateAntiForgeryToken]
public ActionResult Edit(int id, NlcAccount updatedAccount)
{
    try
    {
        var index = nlcListAccount.FindIndex(x => x.NlcId == id);
        if (index >= 0)
        {
            nlcListAccount[index] = updatedAccount;
        }
        return RedirectToAction(nameof(NlcIndex));
    }
    catch
    {
        return View(updatedAccount);
    }
}


        // GET: NlcAccountController/Delete/5
        // GET: NlcAccountController/Delete/5
        public ActionResult Delete(int id)
        {
            var acc = nlcListAccount.FirstOrDefault(x => x.NlcId == id);
            if (acc == null)
            {
                return NotFound();
            }
            return View(acc);
        }

        // POST: NlcAccountController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, lab08.Models.NlcAccount collection)
        {
            try
            {
                var acc = nlcListAccount.FirstOrDefault(x => x.NlcId == id);
                if (acc != null)
                {
                    nlcListAccount.Remove(acc);
                }
                return RedirectToAction(nameof(NlcIndex));
            }
            catch
            {
                return View(collection);
            }
        }

    }
}

lab08/lab08/Controllers/NlcHomeController.cs
using lab08.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace lab08.Controllers
{
    public class NlcHomeController : Controller
    {
        private readonly ILogger<NlcHomeController> _logger;

        public NlcHomeController(ILogger<NlcHomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult NlcIndex()
        {
            return View();
        }

        public IActionResult NlcAbout()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab08/lab08/Views/NlcAccount/Create.cshtml
@model lab08.Models.NlcAccount

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>NlcAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NlcId" class="control-label"></label>
                <input asp-for="NlcId" class="form-control" />
                <span asp-validation-for="NlcId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcFullName" class="control-label"></label>
                <input asp-for="NlcFullName" class="form-control" />
                <span asp-validation-for="NlcFullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcEmail" class="control-label"></label>
                <input asp-for="NlcEmail" class="form-control" />
                <span asp-validation-for="NlcEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcPhone" class="control-label"></label>
                <input asp-for="NlcPhone" class="form-control" />
                <span asp-validation-for="NlcPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcAddress" class="control-label"></label>
                <input asp-for="NlcAddress" class="form-control" />
                <span asp-validation-for="NlcAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcAvatar" class="control-label"></label>
                <input asp-for="NlcAvatar" class="form-control" />
                <span asp-validation-for="NlcAvatar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcBirthday" class="control-label"></label>
                <input asp-for="NlcBirthday" class="form-control" />
                <span asp-validation-for="NlcBirthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcGender" class="control-label"></label>
                <input asp-for="NlcGender" class="form-control" />
                <span asp-validation-for="NlcGender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcPassword" class="control-label"></label>
                <input asp-for="NlcPassword" class="form-control" />
                <span asp-validation-for="NlcPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcFacebook" class="control-label"></label>
                <input asp-for="NlcFacebook" class="form-control" />
                <span asp-validation-for="NlcFacebook" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="NlcIndex">Back to List</a>
</div>

lab08/lab08/Views/NlcAccount/Delete.cshtml
@model lab08.Models.NlcAccount

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NlcAccount</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NlcId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NlcId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NlcFullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NlcFullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NlcEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NlcEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NlcPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NlcPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NlcAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NlcAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NlcAvatar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NlcAvatar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NlcBirthday)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NlcBirthday)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NlcGender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NlcGender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NlcPassword)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NlcPassword)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NlcFacebook)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NlcFacebook)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="NlcIndex">Back to List</a>
    </form>
</div>

lab08/lab08/Views/NlcAccount/Edit.cshtml
@model lab08.Models.NlcAccount

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>NlcAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4" >
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NlcId" class="control-label"></label>
                <input asp-for="NlcId" class="form-control" />
                <span asp-validation-for="NlcId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcFullName" class="control-label"></label>
                <input asp-for="NlcFullName" class="form-control" />
                <span asp-validation-for="NlcFullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcEmail" class="control-label"></label>
                <input asp-for="NlcEmail" class="form-control" />
                <span asp-validation-for="NlcEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcPhone" class="control-label"></label>
                <input asp-for="NlcPhone" class="form-control" />
                <span asp-validation-for="NlcPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcAddress" class="control-label"></label>
                <input asp-for="NlcAddress" class="form-control" />
                <span asp-validation-for="NlcAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcAvatar" class="control-label"></label>
                <input asp-for="NlcAvatar" class="form-control" />
                <span asp-validation-for="NlcAvatar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcBirthday" class="control-label"></label>
                <input asp-for="NlcBirthday" class="form-control" />
                <span asp-validation-for="NlcBirthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcGender" class="control-label"></label>
                <input asp-for="NlcGender" class="form-control" />
                <span asp-validation-for="NlcGender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcPassword" class="control-label"></label>
                <input asp-for="NlcPassword" class="form-control" />
                <span asp-validation-for="NlcPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NlcFacebook" class="control-label"></label>
                <input asp-for="NlcFacebook" class="form-control" />
                <span asp-validation-for="NlcFacebook" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />

            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="NlcIndex">Back to List</a>
</div>

lab08/lab08/Views/NlcAccount/NlcIndex.cshtml
@model IEnumerable<lab08.Models.NlcAccount>

@{
    ViewData["Title"] = "NlcIndex";
}

<h1>NlcIndex</h1>

<p>
    <a asp-action="Create" class="btn btn-danger" >Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NlcId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NlcFullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NlcEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NlcPhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NlcAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NlcAvatar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NlcBirthday)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NlcGender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NlcPassword)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NlcFacebook)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NlcId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NlcFullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NlcEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NlcPhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NlcAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NlcAvatar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NlcBirthday)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NlcGender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NlcPassword)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NlcFacebook)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.NlcId }) |

                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.NlcId })

            </td>
        </tr>
}
    </tbody>
</table>

lab08/lab08/Views/Shared/Nlc_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lab08</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lab08.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="NlcHome" asp-action="NlcIndex">lab08</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NlcHome" asp-action="NlcIndex">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NlcHome" asp-action="NlcAbout">thong tin sinh vien </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NlcAccount" asp-action="NlcIndex">danh sach tai khoan </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - lab08 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>